const productos = [
  {
    id: 01,
    tipo: "Bolsas",
    nombre: "CEMENTO EXTRA HIDRAT X 25 KG",
    precio: 1400,
    foto: " ",
  },
  {
    id: 02,
    tipo: "Bolsas",
    nombre: "CAL MILAGRO X 25 KG",
    precio: 1400,
    foto: " ",
  },
  {
    id: 03,
    tipo: "Bolsas",
    nombre: "CEMENTO LOMA NEGRA X 50 KG",
    precio: 1000,
    foto: " ",
  },
  {
    id: 04,
    tipo: "Bolsas",
    nombre: "CEMENTO HOLCIM X 50 KG",
    precio: 1000,
    foto: " ",
  },
  {
    id: 05,
    tipo: "Bolsas",
    nombre: "PLASTICOR X 50 KG",
    precio: 1400,
    foto: " ",
  },
  {
    id: 06,
    tipo: "Bolsas",
    nombre: "WEBER IMPERMEABLE X 30 KG",
    precio: 1500,
    foto: " ",
  },
  {
    id: 07,
    tipo: "Bolsas",
    nombre: "WEBER PORCELANATO X 30 KG",
    precio: 4500,
    foto: " ",
  },
  {
    id: 08,
    tipo: "Ladrillo",
    nombre: "LADRILLO COMUN",
    precio: 3800,
    foto: " ",
  },
  {
    id: 09,
    tipo: "Ladrillo",
    nombre: "LADRILLO HUECO 12 X 18 X 33",
    precio: 3800,
    foto: " ",
  },
  {
    id: 10,
    tipo: "Ladrillo",
    nombre:
      "LADRILLO CORDOBA",
    precio: 3800,
    foto: " ",
  },
  {
    id: 11,
    tipo: "Ladrillo",
    nombre:
      "LADRILLO DE TELGOPOR 10 CM",
    precio: 2900,
    foto: " ",
  },
  {
    id: 13,
    tipo: "Ladrillo",
    nombre: "LADRILLO DE TELGOPOR 12 CM",
    precio: 1000,
    foto: " ",
  },
  {
    id: 14,
    tipo: "Ladrillo",
    nombre: "LADRILLO HUECO 8 X 18 X 33",
    precio: 1300,
    foto: " ",
  },
  {
    id: 15,
    tipo: "Ladrillo",
    nombre: "PORTANTE 12",
    precio: 2300,
    foto: " ",
  },
  {
    id: 16,
    tipo: "Ladrillo",
    nombre: "PORTANTE 18",
    precio: 2400,
    foto: " ",
  },
  {
    id: 17,
    tipo: "Hierros",
    nombre: "CHAPAS ACANALADAS",
    precio: 800,
    foto: "",
  },
  {
    id: 18,
    tipo: "Hierros",
    nombre: "CLAVO PUNTA PARIS",
    precio: 800,
    foto: "",
  },
  {
    id: 19,
    tipo: "Hierros",
    nombre: "HIERRO DEL 10",
    precio: 800,
    foto: " ",
  },
  {
    id: 20,
    tipo: "Hierros",
    nombre: "HIERRO DEL 12",
    precio: 800,
    foto: " ",
  },
  {
    id: 21,
    tipo: "Hierros",
    nombre: "HIERRO DEL 16",
    precio: 800,
    foto: " ",
  },
  {
    id: 22,
    tipo: "Hierros",
    nombre: "HIERRO DEL 6",
    precio: 800,
    foto: " ",
  },
  {
    id: 23,
    tipo: "Hierros",
    nombre: "HIERRO DEL 8",
    precio: 800,
    foto: " ",
  },
  {
    id: 24,
    tipo: "Hierros",
    nombre: "MALLA 15 X 15 DEL 8",
    precio: 800,
    foto: " ",
  },
  {
    id: 25,
    tipo: "Hierros",
    nombre: "MALLAS 15 X 15 4,2",
    precio: 800,
    foto: " ",
  },
  {
    id: 26,
    tipo: "Hierros",
    nombre: "MALLAS 15 X 15 6",
    precio: 800,
    foto: " ",
  },
  {
    id: 27,
    tipo: "Hierros",
    nombre: "TUBO ESTRUCTURAL RECTANGULAR",
    precio: 800,
    foto: " ",
  },
  {
    id: 28,
    tipo: "Hierros",
    nombre: "TUBOS ESTRUCTURALES",
    precio: 800,
    foto: " ",
  },
  {
    id: 29,
    tipo: "Vigueta",
    nombre: "VIGUETA 2,00 MTS",
    precio: 800,
    foto: "",
  },
  {
    id: 30,
    tipo: "Vigueta",
    nombre: "VIGUETA 2,20 MTS",
    precio: 800,
    foto: "",
  },
  {
    id: 31,
    tipo: "Vigueta",
    nombre: "VIGUETA 2,40 MTS",
    precio: 800,
    foto: "",
  },
  {
    id: 32,
    tipo: "Vigueta",
    nombre: "VIGUETA 2,60 MTS",
    precio: 800,
    foto: "",
  },
  {
    id: 33,
    tipo: "Vigueta",
    nombre: "VIGUETA 2,80 MTS",
    precio: 800,
    foto: "",
  },
  {
    id: 34,
    tipo: "Vigueta",
    nombre: "VIGUETA 3,00 MTS",
    precio: 800,
    foto: "",
  },
  {
    id: 35,
    tipo: "Vigueta",
    nombre: "VIGUETA 3,20 MTS",
    precio: 800,
    foto: "",
  },
  {
    id: 36,
    tipo: "Vigueta",
    nombre: "VIGUETA 3,40 MTS",
    precio: 800,
    foto: "",
  },
  {
    id: 37,
    tipo: "Vigueta",
    nombre: "VIGUETA 3,60 MTS",
    precio: 800,
    foto: "",
  },
  {
    id: 38,
    tipo: "Vigueta",
    nombre: "VIGUETA 3,80 MTS",
    precio: 800,
    foto: "",
  },
  {
    id: 39,
    tipo: "Vigueta",
    nombre: "VIGUETA 4,00 MTS",
    precio: 800,
    foto: "",
  },
  {
    id: 40,
    tipo: "Vigueta",
    nombre:
      "VIGUETA 4,40 MTS",
    precio: 800,
    foto: "",
  },
  {
    id: 41,
    tipo: "Vigueta",
    nombre: "VIGUETA 4,60 MTS",
    precio: 800,
    foto: "",
  },
];
